repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=100"]
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
    -   id: black
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    -   id: isort
-   repo: https://github.com/kynan/nbstripout
    rev: 0.4.0
    hooks:
    -   id: nbstripout
        exclude: '*_experiment.ipynb'
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.11.1
    hooks:
    -   id: nbqa-black
        args: ["--nbqa-mutate"]
    -   id: nbqa-isort
        args: ["--nbqa-mutate"]
